name: upload files to Live server through FTP
on:
  push:
    branches:
      - main
jobs:
  FTP-deploy-action:
    name: FTP-deploy-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
         server: ${{ secrets.FTP_SERVER}}
         username: ${{ secrets.FTP_USERNAME}}
         password: ${{ secrets.FTP_PASSWORD}}
